version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=games_io
      - MYSQL_USER=games_io
      - MYSQL_PASSWORD=${DB_PASSWORD}
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    expose:
      - 6379
  games-io-api:
    build: .
    ports:
      - 8080:8080
    expose:
      - 8080
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATASOURCE_NAME=${DB_DATASOURCE_NAME}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=6379
      - REDIS_TIMEOUT=60000
      - JWT_API_SECRET=${JWT_API_SECRET}
      - EMAIL_ADDRESS=${EMAIL_ADDRESS}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    depends_on:
      - mysql
      - redis
