version: '3'
services:
  redis-games-io:
    image: 'redis:latest'
    ports:
      - 6379:6379
  mysql-games-io:
    image: 'mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=games_io
    ports:
      - 3306:3306
  springboot-docker-container:
    image: springboot-docker-container
    ports:
      - 80:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-games-io:3306/games_io?autoReconnect=true&useSSL=false
      DB_USERNAME: root
      DB_PASSWORDD: root
      DB_DATASOURCE_NAME: GamesIoDataSource
      REDIS_HOST: 127.0.0.1
      REDIS_PORT: 6379
      REDIS_TIMEOUT: 60000
    build:
      context: "./"
      dockerfile: "DockerFile"
    depends_on:
      - mysql-games-io
      - redis-games-io