spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    name: ${DB_DATASOURCE_NAME}
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  cache:
    type: redis
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    timeout: ${REDIS_TIMEOUT}
  mail:
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_PASSWORD}

server:
  error:
    include-message: always
    include-binding-errors: always

jwt:
  api:
    secret: ${JWT_API_SECRET}