
name: Deploy docker compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the docker-compose
        run: docker-compose up -d --build

  deploy:
    needs: build
    
    runs-on: ubuntu-latest
    
    steps: 
    
      - name: Deploy docker compose
      
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.SSH_HOSTNAME  }}
            USER_NAME : ${{ secrets.SSH_USERNAME  }}
            
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${SSH_USERNAME}@${SSH_HOSTNAME} '
          
            cd /home/ubuntu/GamesIoApi/games-io-api &&
            git checkout main &&
            git fetch --all &&
            git reset --hard origin/master &&
            git pull origin master &&
            docker-compose -f docker-compose.yml up -d --build 
          '
